file_extensions:
  - jpg
  - png
  - gif
keys:
  - Artist
  - Make
  - Model
  - BodySerialNumber
  - DateTime
  - DateTimeOriginal
  - DateTimeDigitized
  - latitude
  - longitude
  - GPSInfo
  - ApertureValue
  - BodySerialNumber
  - BodySerialNumber
  - CameraOwnerName
  - ColorSpace
  - ComponentsConfiguration
  - CompressedBitsPerPixel
  - Contrast
  - Copyright
  - CustomRendered
  - DigitalZoomRatio
  - ExifImageHeight
  - ExifImageWidth
  - ExifOffset
  - ExifVersion
  - ExposureMode
  - ExposureProgram
  - ExposureTime
  - FileSource
  - Flash
  - FNumber
  - FocalLength
  - FocalLengthIn35mmFilm
  - FocalPlaneResolutionUnit
  - FocalPlaneXResolution
  - FocalPlaneYResolution
  - GainControl
  - ISOSpeedRatings
  - LensModel
  - LensSpecification
  - LightSource
  - MaxApertureValue
  - MeteringMode
  - Orientation
  - PrintImageMatching
  - Saturation
  - SceneCaptureType
  - SceneType
  - SensingMethod
  - Sharpness
  - ShutterSpeedValue
  - Software
  - Software
  - SubsecTimeDigitized
  - SubsecTimeOriginal
  - WhiteBalance
  - YCbCrPositioning
  - ResolutionUnit
  - XResolution
  - YResolution
ignore_keys:
  - MakerNote  # http://www.ozhiker.com/electronics/pjmt/jpeg_info/panasonic_mn.html
  - ExposureBiasValue
  - SubsecTimeOriginal
  - ExifInteroperabilityOffset
  - FlashPixVersion
